import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public cards: Array<any> = [
    { "name": "Adael Oliveira", "location": "Presidente Prudente", "joinedGroupOn": "12/18/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/244156736/" },
    { "name": "Adiane", "location": "Rio de Janeiro", "joinedGroupOn": "02/04/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/94853272/" },
    { "name": "Afonso Tessari Ferreira", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243693250/" },
    { "name": "Alessandro Altino", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/201072348/" },
    { "name": "Alex Mota", "location": "Presidente Prudente", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243780452/" },
    { "name": "Allan Albuquerque", "location": "Presidente Prudente", "joinedGroupOn": "02/02/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247399408/" },
    { "name": "Anderson Vincoletto", "location": "Presidente Prudente", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243903087/" },
    { "name": "Andressa Gouveia", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243713570/" },
    { "name": "André Hungaro", "location": "Vancouver, BC", "joinedGroupOn": "02/13/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/198473852/" },
    { "name": "André Ozawa", "location": "Presidente Prudente", "joinedGroupOn": "02/15/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/248276095/" },
    { "name": "Augusto César", "location": "MarÃ­lia", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243902464/" },
    { "name": "Breno S. Beletato", "location": "Presidente Prudente", "joinedGroupOn": "02/15/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/248281509/" },
    { "name": "Bruno Vinicius Manfrão", "location": "Presidente Prudente", "joinedGroupOn": "01/23/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246669036/" },
    { "name": "Caio Russi", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243696787/" },
    { "name": "Camila Polizello", "location": "Presidente Prudente", "joinedGroupOn": "02/11/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/248012967/" },
    { "name": "Carlos Martins", "location": "Presidente Prudente", "joinedGroupOn": "02/09/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247859861/" },
    { "name": "Cido Araujo", "location": "Presidente Prudente", "joinedGroupOn": "12/19/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/244208665/" },
    { "name": "Claudemir Lima", "location": "Presidente Prudente", "joinedGroupOn": "12/10/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243638311/" },
    { "name": "Daniel Eletronic+IoT+blockchain", "location": "Presidente Prudente", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/213214420/" },
    { "name": "Daniel Trondoli", "location": "Presidente Prudente", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243783067/" },
    { "name": "Darcio Gusman", "location": "Presidente Prudente", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243928409/" },
    { "name": "Deyvisson Pinheiro", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243694502/" },
    { "name": "Diego Machado", "location": "Presidente Prudente", "joinedGroupOn": "12/19/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/244208247/" },
    { "name": "DR FABIANO Teranisi", "location": "Presidente Prudente", "joinedGroupOn": "08/18/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/234382186/" },
    { "name": "Edson Welington", "location": "Presidente Prudente", "joinedGroupOn": "08/10/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/233728242/" },
    { "name": "Eduardo Lopes", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243722185/" },
    { "name": "Emanuel Henrique", "location": "Presidente Prudente", "joinedGroupOn": "12/20/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/244288714/" },
    { "name": "Emanuel Herique Magri da Silva", "location": "Presidente Prudente", "joinedGroupOn": "01/23/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246667174/" },
    { "name": "Emerson Miyasaki", "location": "Presidente Prudente", "joinedGroupOn": "01/24/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246785916/" },
    { "name": "Enrique Prieto", "location": "SÃ£o Paulo", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/219852879/" },
    { "name": "Felipe", "location": "Presidente Prudente", "joinedGroupOn": "12/23/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/244249934/" },
    { "name": "Felipe Albuquerque de Almeida", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243678940/" },
    { "name": "Felipe Benincasa", "location": "Presidente Prudente", "joinedGroupOn": "01/22/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246629819/" },
    { "name": "Felipe Blini", "location": "Presidente Prudente", "joinedGroupOn": "07/31/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/171930182/" },
    { "name": "Felipe Vicente", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243698808/" },
    { "name": "Fernanda de Almeida", "location": "Santo AnastÃ¡cio", "joinedGroupOn": "01/23/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246699690/" },
    { "name": "Fernando Cassinelli", "location": "Presidente Prudente", "joinedGroupOn": "02/02/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247390200/" },
    { "name": "Fernando Modafaris de Araujo", "location": "Presidente Prudente", "joinedGroupOn": "01/25/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246821980/" },
    { "name": "Fernando Vicente", "location": "Presidente Prudente", "joinedGroupOn": "01/24/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246788344/" },
    { "name": "Fábio Costa", "location": "Presidente Prudente", "joinedGroupOn": "08/01/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/198700472/" },
    { "name": "Fábio T. Perez", "location": "Presidente Prudente", "joinedGroupOn": "01/23/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246716895/" },
    { "name": "Gabriel Branquinho", "location": "SÃ£o Paulo", "joinedGroupOn": "02/13/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247899396/" },
    { "name": "Gabriel Fredo", "location": "Presidente Prudente", "joinedGroupOn": "08/03/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/233231503/" },
    { "name": "Gabriel Furlan", "location": "SÃ£o Paulo", "joinedGroupOn": "01/25/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/221828194/" },
    { "name": "Gabriel Majaron", "location": "Presidente Prudente", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243757384/" },
    { "name": "Geiziane", "location": "Presidente Prudente", "joinedGroupOn": "01/31/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247277047/" },
    { "name": "Guilherme Alexandre", "location": "Presidente Prudente", "joinedGroupOn": "08/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/234058889/" },
    { "name": "Guilherme Cavichioli", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243692886/" },
    { "name": "Guilherme H. L. Santos", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243707023/" },
    { "name": "Gustavo Marquini", "location": "Campinas", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/13572281/" },
    { "name": "Gustavo Sasaki", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243695499/" },
    { "name": "Haroldo Teruya", "location": "Presidente Prudente", "joinedGroupOn": "01/26/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246901279/" },
    { "name": "Henrique Cunha", "location": "Presidente Prudente", "joinedGroupOn": "01/22/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246637248/" },
    { "name": "Igor Ludgero Miura", "location": "Presidente Prudente", "joinedGroupOn": "12/26/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/218113203/" },
    { "name": "Igor Yamashita", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243693161/" },
    { "name": "Isabela Santos", "location": "Presidente Prudente", "joinedGroupOn": "02/02/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247364493/" },
    { "name": "J.VALDERIO SANTOS", "location": "Presidente Prudente", "joinedGroupOn": "12/10/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/192324026/" },
    { "name": "Jean Dias", "location": "Presidente Prudente", "joinedGroupOn": "01/31/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247274041/" },
    { "name": "Jeffrey Bittencourt", "location": "Presidente Prudente", "joinedGroupOn": "12/19/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/244215670/" },
    { "name": "Jessica Aparecida Amorim", "location": "Presidente Prudente", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/207340870/" },
    { "name": "Jonatas Zito", "location": "Pirapozinho", "joinedGroupOn": "01/23/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246669560/" },
    { "name": "José Pascoal Vernilo", "location": "Presidente Prudente", "joinedGroupOn": "01/25/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/232120697/" },
    { "name": "João Cunha", "location": "Dubai", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/160518752/" },
    { "name": "João Hernandes", "location": "Presidente Prudente", "joinedGroupOn": "12/13/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243819418/" },
    { "name": "João Lossi", "location": "Presidente Prudente", "joinedGroupOn": "01/29/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247101611/" },
    { "name": "João Maiorchini", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243692903/" },
    { "name": "Juliana Peixoto", "location": "Presidente Bernardes", "joinedGroupOn": "11/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/241022886/" },
    { "name": "Junior CS", "location": "Presidente Prudente", "joinedGroupOn": "01/28/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/181996192/" },
    { "name": "Junior Rota", "location": "Presidente Prudente", "joinedGroupOn": "02/06/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/185111685/" },
    { "name": "Jéssica Takazono", "location": "Presidente Prudente", "joinedGroupOn": "11/23/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/217943994/" },
    { "name": "Kako Fernandes", "location": "SÃ£o Paulo", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/65875232/" },
    { "name": "Kleiton Rogério", "location": "SÃ£o Paulo", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243932068/" },
    { "name": "Leandro Blazão", "location": "Londrina", "joinedGroupOn": "09/21/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/183579862/" },
    { "name": "Leandro Mariano Barbosa", "location": "Presidente Prudente", "joinedGroupOn": "01/29/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247104663/" },
    { "name": "Leonardo Henrique", "location": "Presidente Prudente", "joinedGroupOn": "08/07/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/233493620/" },
    { "name": "Leonardo Lucas Ferreira", "location": "Presidente Prudente", "joinedGroupOn": "01/23/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246666909/" },
    { "name": "Leonardo Ochoa Lopes", "location": "SÃ£o Paulo", "joinedGroupOn": "01/30/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/239620352/" },
    { "name": "Leonardo Vox", "location": "Presidente Prudente", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243754836/" },
    { "name": "Letícia Sene", "location": "Presidente Prudente", "joinedGroupOn": "02/08/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247776681/" },
    { "name": "Lucas", "location": "Santo AnastÃ¡cio", "joinedGroupOn": "02/02/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247363850/" },
    { "name": "Lucas Alves", "location": "Presidente Prudente", "joinedGroupOn": "09/30/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/237795911/" },
    { "name": "Lucas Azambuja", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/191322877/" },
    { "name": "Lucas Manuel", "location": "Presidente Prudente", "joinedGroupOn": "01/25/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246808244/" },
    { "name": "Luciano Honorio Ferreira", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243701768/" },
    { "name": "Luiz Filipe Monge", "location": "Presidente Prudente", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/227216829/" },
    { "name": "Luiz Paulo Wince Teixeira", "location": "Presidente Prudente", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243730320/" },
    { "name": "Marcela Maciel Brandão", "location": "Presidente Prudente", "joinedGroupOn": "02/01/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/207952747/" },
    { "name": "Marcelo", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243695012/" },
    { "name": "Marcelo Lima", "location": "Presidente Prudente", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/242516182/" },
    { "name": "Marcelo Rosa", "location": "Presidente Prudente", "joinedGroupOn": "12/10/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243629126/" },
    { "name": "Marcelo Santoro", "location": "Presidente Prudente", "joinedGroupOn": "01/22/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246638588/" },
    { "name": "Marcelo Soares", "location": "Presidente Prudente", "joinedGroupOn": "01/23/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246656696/" },
    { "name": "Marco Aurélio Munhóz", "location": "Regente FeijÃ³", "joinedGroupOn": "01/27/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/217107362/" },
    { "name": "Marcos Ferreira", "location": "Presidente Prudente", "joinedGroupOn": "10/15/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/238972662/" },
    { "name": "MARCOS HÚNGARO", "location": "Presidente Prudente", "joinedGroupOn": "09/20/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/237001234/" },
    { "name": "Marcos Oliverlima", "location": "Presidente Prudente", "joinedGroupOn": "09/28/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/237673236/" },
    { "name": "Marlon Araújo", "location": "Presidente Prudente", "joinedGroupOn": "01/23/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246702950/" },
    { "name": "Mauricio Souza", "location": "Presidente Prudente", "joinedGroupOn": "12/19/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/244221179/" },
    { "name": "Miguel Watanabe", "location": "Rancharia", "joinedGroupOn": "11/18/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/241613496/" },
    { "name": "Murilo Siqueira Ferreira", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243691746/" },
    { "name": "Nathália Puglisi", "location": "Presidente Prudente", "joinedGroupOn": "01/31/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247273096/" },
    { "name": "Otávio Corrêa", "location": "Presidente Prudente", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243753958/" },
    { "name": "Pablo Coitino", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243698588/" },
    { "name": "Paulo Carneiro", "location": "Presidente Prudente", "joinedGroupOn": "01/24/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246784259/" },
    { "name": "Paulo Lino Junior", "location": "Presidente Prudente", "joinedGroupOn": "02/05/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247604511/" },
    { "name": "Paulo Sérgio Diniz", "location": "Presidente Prudente", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243900884/" },
    { "name": "Paulo Sérgio Diniz", "location": "Presidente Prudente", "joinedGroupOn": "01/22/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246629017/" },
    { "name": "Paulo Tarocchi", "location": "Presidente Prudente", "joinedGroupOn": "12/20/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/244277121/" },
    { "name": "Pedro Silva", "location": "Presidente Prudente", "joinedGroupOn": "01/25/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246821626/" },
    { "name": "Pedro Vicari", "location": "Presidente Prudente", "joinedGroupOn": "01/24/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246740296/" },
    { "name": "Pedro Vinicius", "location": "Presidente Prudente", "joinedGroupOn": "01/23/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246699195/" },
    { "name": "Phillipe Sant'Ana", "location": "Presidente Prudente", "joinedGroupOn": "12/19/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/244245130/" },
    { "name": "Porfirio Rodrigues", "location": "Presidente Prudente", "joinedGroupOn": "01/30/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247174669/" },
    { "name": "Priscila Gualdi Pantarotto", "location": "Presidente Prudente", "joinedGroupOn": "02/07/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/234710051/" },
    { "name": "Rafael Araujo", "location": "Presidente Prudente", "joinedGroupOn": "01/29/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247099074/" },
    { "name": "Rafael Jacomeli", "location": "Presidente Prudente", "joinedGroupOn": "12/10/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243630725/" },
    { "name": "Rafhael Alkimim C Andrade", "location": "Presidente Prudente", "joinedGroupOn": "02/02/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247383829/" },
    { "name": "Renan Pupin", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243692697/" },
    { "name": "Ricardo Tangerino de Souza", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243694276/" },
    { "name": "Ricardo Veiga", "location": "Presidente Prudente", "joinedGroupOn": "09/18/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/197688987/" },
    { "name": "Roberto Júnior", "location": "Presidente Prudente", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/194594402/" },
    { "name": "Rogger Borges", "location": "Presidente Prudente", "joinedGroupOn": "01/26/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246913881/" },
    { "name": "Rogério Do Carmo", "location": "Presidente Prudente", "joinedGroupOn": "02/08/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/247783481/" },
    { "name": "Sandro Ramone", "location": "Presidente Prudente", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243905922/" },
    { "name": "Sino Pessoal", "location": "Presidente Prudente", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243917263/" },
    { "name": "Sinomar Calmona", "location": "Presidente Prudente", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243916963/" },
    { "name": "Stéfano H", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243689849/" },
    { "name": "Thiago Calistro", "location": "SÃ£o Paulo", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/130219502/" },
    { "name": "Thiago De Carlo Gonçalves", "location": "Presidente Prudente", "joinedGroupOn": "01/23/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246665192/" },
    { "name": "Thiaguinho Bahia", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/56593552/" },
    { "name": "Valter Rodrigues de Souza", "location": "Osvaldo Cruz", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243772260/" },
    { "name": "Valter VinÃ­cius", "location": "Vancouver, BC", "joinedGroupOn": "02/05/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/207715632/" },
    { "name": "Valério", "location": "Presidente Prudente", "joinedGroupOn": "09/18/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/199376911/" },
    { "name": "Victor Damaceno", "location": "SÃ£o Paulo", "joinedGroupOn": "01/29/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/220495561/" },
    { "name": "Victor Santos", "location": "QuÃ©bec, QC", "joinedGroupOn": "12/25/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/229346526/" },
    { "name": "Vinicius Teixeira", "location": "Presidente Prudente", "joinedGroupOn": "01/25/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246822607/" },
    { "name": "Vitor Scobin", "location": "Presidente Prudente", "joinedGroupOn": "12/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243900898/" },
    { "name": "Viviane Marques de Carvalho", "location": "Presidente Prudente", "joinedGroupOn": "01/25/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/246835072/" },
    { "name": "Vânia Cristina da Silva", "location": "JaguariÃºna", "joinedGroupOn": "12/12/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243747425/" },
    { "name": "Walmir Carvalho", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243690034/" },
    { "name": "William Fernando", "location": "Presidente Prudente", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/243693499/" },
    { "name": "Yuri Rodrigues", "location": "Presidente Prudente", "joinedGroupOn": "08/14/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/234060979/" },
    { "name": "Érica Betto Sene", "location": "MartinÃ³polis", "joinedGroupOn": "12/11/2017", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/163588852/" },
    { "name": "Ériton Oliveira Silva", "location": "Presidente Prudente", "joinedGroupOn": "02/14/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/248224502/" },
    { "name": "á–‡á•®á˜‰á—©á˜‰ á™–á‘Œá—©á–‡á–‡á—©á’Ž", "location": "Presidente Prudente", "joinedGroupOn": "01/26/2018", "urlOfMemberProfile": "https://www.meetup.com/dev-pp/members/191323019/" },
  ];
}
